openapi: 3.0.0
info:
  version: 1.0.0
  title: Users API
  license:
    name: Test
paths:
  /login/:
    post:
      operationId: services.login.user.class_instance.login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: 'Login Info'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: 'Failed'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
servers:
  - url: /v1.0/user
components:
  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
         type: string
        password:
         type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string